import Head from "next/head";

const Home = () => {
  return (
    <div className="container">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title>GuitarLa</title>
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <h1>Hello Next.js</h1>
    </div>
  );
};

export default Home;
